# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20161014_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='udpate_time',
            new_name='update_time',
        ),
    ]
